# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: deploy
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  release:
    types: [ published ]

env:
  PUBLISH_OUTPUT_DIR: './publish'
  REMOTE_APP_DIR: '/www/demo.auth.myvas.com'
  SERVICE_NAME: 'demo.auth.myvas.com'
  SSH_HOST: 'demo.auth.myvas.com'
  SSH_USERNAME: 'deploy-myvas-auth-demo'

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/MvcDemo --configuration Release --runtime linux-x64 --framework net8.0 --output ${{ env.PUBLISH_OUTPUT_DIR }}

      - name: Stop the service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |            
            sudo systemctl stop ${{ env.SERVICE_NAME }} || true

      - name: Save the SSH private key to a file
        run: |
          whoami
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy the published app to the server
        run: |
            rsync --version
            rsync -avz --exclude 'demo.sqlite' -e "ssh -i ~/.ssh/id_rsa" ${{ env.PUBLISH_OUTPUT_DIR }}/ ${{ env.SSH_USERNAME }}@${{ env.SSH_HOST }}:${{ env.REMOTE_APP_DIR }}/

            # Set permissions
            sudo chown -R '${{ env.SSH_USERNAME }}':'www-data' ${{ env.REMOTE_APP_DIR }}
            sudo chmod -R 775 ${{ env.REMOTE_APP_DIR }}

      - name: Start the service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |       
            # Restart the service (if applicable)
            sudo systemctl start ${{ env.SERVICE_NAME }}
      
